server:
  port: 1002

spring:
  datasource:
    url: jdbc:postgresql://localhost:2002/users_db
    username: postgres
    password: j@vacefer2005
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
